# Generated by Django 6.0.7 on 2026-07-26 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlotFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="plot",
            name="block",
            field=models.CharField(
                blank=True, help_text="Block/Sector e.g. A, B, C", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="facing_direction",
            field=models.CharField(
                blank=True, help_text="North/South/East/West", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="holding_deposit",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Required token/holding amount",
                max_digits=15,
            ),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_corner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="is_park_facing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plot",
            name="street_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="plot",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("on_hold", "On Hold"),
                    ("booked", "Booked"),
                    ("sold", "Sold"),
                    ("cancelled", "Cancelled"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PlotDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="plot_documents/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="properties.plot",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plot",
            name="features",
            field=models.ManyToManyField(blank=True, to="properties.plotfeature"),
        ),
        migrations.CreateModel(
            name="PlotImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="plot_imports/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True)),
                ("plots_created", models.PositiveIntegerField(default=0)),
                ("plots_failed", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("change_reason", models.CharField(blank=True, max_length=100)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="properties.plot",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price Histories",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("launch_date", models.DateField()),
                ("total_plots", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price_per_marla",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="properties.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plot",
            name="phase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="plots",
                to="properties.projectphase",
            ),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(fields=["status"], name="properties__status_c00bee_idx"),
        ),
        migrations.AddIndex(
            model_name="plot",
            index=models.Index(
                fields=["project", "status"], name="properties__project_51e318_idx"
            ),
        ),
    ]
