# Generated by Django 6.0.7 on 2026-07-26 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_cancellationpolicy_booking_cancellation_fee_and_more"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("booking", "New Booking"),
                            ("payment", "Payment Received"),
                            ("refund", "Refund Issued"),
                            ("late_fee", "Late Fee Applied"),
                            ("waiver", "Late Fee Waived"),
                            ("discount", "Discount Applied"),
                            ("transfer_in", "Transfer In"),
                            ("transfer_out", "Transfer Out"),
                            ("adjustment", "Manual Adjustment"),
                            ("reversal", "Entry Reversal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=50)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "running_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("description", models.TextField(blank=True)),
                ("entry_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Customer Ledger Entries",
                "ordering": ["entry_date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReceivableAging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("days_overdue", models.IntegerField(default=0)),
                (
                    "aging_bucket",
                    models.CharField(
                        choices=[
                            ("current", "Current (0-30)"),
                            ("1_30", "1-30 Days"),
                            ("31_60", "31-60 Days"),
                            ("61_90", "61-90 Days"),
                            ("90_plus", "90+ Days"),
                        ],
                        max_length=20,
                    ),
                ),
                ("computed_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["cnic"], name="customers_c_cnic_dc9fff_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["phone"], name="customers_c_phone_8493fa_idx"),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerledgerentry",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ledger_entries",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="receivableaging",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="bookings.booking"
            ),
        ),
        migrations.AddField(
            model_name="receivableaging",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customers.customer"
            ),
        ),
        migrations.AddIndex(
            model_name="customerledgerentry",
            index=models.Index(
                fields=["customer", "entry_date"], name="customers_c_custome_111d74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerledgerentry",
            index=models.Index(
                fields=["booking", "entry_date"], name="customers_c_booking_e4ca4f_idx"
            ),
        ),
    ]
