# Generated by Django 6.0.7 on 2026-07-26 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("customers", "0001_initial"),
        ("properties", "0002_plotfeature_plot_block_plot_facing_direction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CancellationPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_possession_taken",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="possession_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("walk_in", "Walk-In"),
                    ("referral", "Referral"),
                    ("agent", "Agent"),
                    ("other", "Other"),
                ],
                default="walk_in",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="installment",
            name="payment_allocation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Audit trail of which payments covered this installment",
            ),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="down_payment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("half_yearly", "Half-Yearly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="grace_period_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="last_auto_processed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="total_late_fee_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="installmentplan",
            name="installment_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name="BookingAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("old_value", models.TextField()),
                ("new_value", models.TextField()),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amendments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_id",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("payment_plan", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_groups",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="bookings.bookinggroup",
            ),
        ),
        migrations.CreateModel(
            name="BookingTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "previous_payments_handling",
                    models.CharField(
                        choices=[
                            ("transfer", "Transfer to New Customer"),
                            ("refund", "Refund to Original Customer"),
                        ],
                        default="transfer",
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="bookings.booking",
                    ),
                ),
                (
                    "from_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="customers.customer",
                    ),
                ),
                (
                    "to_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="customers.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="cancellation_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.cancellationpolicy",
            ),
        ),
        migrations.CreateModel(
            name="CancellationTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_days",
                    models.IntegerField(help_text="Days from booking date (inclusive)"),
                ),
                (
                    "to_days",
                    models.IntegerField(help_text="Days from booking date (inclusive)"),
                ),
                (
                    "refund_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("deduction_notes", models.TextField(blank=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="bookings.cancellationpolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["from_days"],
            },
        ),
        migrations.CreateModel(
            name="EarlySettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remaining_installments", models.PositiveIntegerField()),
                (
                    "total_remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "settlement_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("approved", models.BooleanField(default=False)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="early_settlements",
                        to="bookings.installmentplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstallmentPlanTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("total_installments", models.PositiveIntegerField()),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half-Yearly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "down_payment_percentage",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                ("has_balloon_payment", models.BooleanField(default=False)),
                (
                    "balloon_installment_number",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "balloon_multiplier",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_templates",
                        to="properties.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="installmentplan",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bookings.installmentplantemplate",
            ),
        ),
        migrations.CreateModel(
            name="InstallmentReschedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_due_date", models.DateField()),
                ("new_due_date", models.DateField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_request", "Customer Request"),
                            ("financial_hardship", "Financial Hardship"),
                            ("system_error", "System Error"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rescheduled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "new_installment_count",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "new_installment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookings.installment",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reschedules",
                        to="bookings.installmentplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LateFeeConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("per_day", "Per Day Fixed"),
                            ("per_day_percentage", "Percentage Per Day"),
                            ("monthly_percentage", "Monthly Percentage"),
                            ("tiered", "Tiered"),
                        ],
                        default="per_day",
                        max_length=20,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_late_fee_per_installment",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "min_late_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("waiver_allowed", models.BooleanField(default=True)),
                ("tiered_rules", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="late_fee_config",
                        to="bookings.installmentplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming Due Reminder"),
                            ("overdue", "Overdue Reminder"),
                            ("grace_period", "Grace Period Ending"),
                            ("late_fee", "Late Fee Applied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_via",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email"), ("both", "Both")],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("delivery_status", models.CharField(default="pending", max_length=20)),
                (
                    "installment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="bookings.installment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("converted", "Converted to Booking"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="customers.customer",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="properties.plot",
                    ),
                ),
            ],
        ),
    ]
